# Generated by Django 5.1.1 on 2024-09-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20200419_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
